Updt:	Update README
42-Madrid-Maker-League/github_colab pull request #30
Opened 2022-11-09 00:51 UTC by iagudo-d

- Added new colaborator to README.md -- "iagudo-d"

2022-11-10 18:49 UTC, bazuara requested changes
Hola! No te adelantes en el readme, los links van a venir después 😄 
Cambia a tu nombre y verifica que no tiene conflictos, así podremos aceptar la MR

2022-11-10 22:11 UTC, closed without merging

2022-11-11 16:29 UTC, bazuara commented
Pero porqué haces force push a un repo que no gestionas????

2022-11-11 16:50 UTC, iagudo-d commented
No hice ningún push force, lo que hice es a mí fork un fetch para
actualizar los cambios de repo original, luego hice un mergue en mi rama
main y lo que ocurrió, que no lo he entendido bien, se realizó un push
force eliminando de manera forzada mi pull-request, por eso, una vez
actualizado mí fork he hecho otro pull-request al repo original. Tengo que
entender ,y si tú sabes algo al respecto del porqué al hacer yo un fetch y
un mergue en mi fork git hub se ha realizado una eliminación forzada de mi
anterior request.
Gracias y sorry.
Para eso estamos, para aprender.

El vie., 11 nov. 2022 17:29, Bruno Azuara ***@***.***>
escribió:

> Pero porqué haces force push a un repo que no gestionas????
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/42-Madrid-Maker-League/github_colab/pull/30#issuecomment-1311920759>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3A74GF3UJCEVTQ7J7K7MXLWHZX7DANCNFSM6AAAAAAR243LJA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>

2022-11-11 16:58 UTC, bazuara commented
Claro, sin problema, por eso te pregunto que porqué haces un force. Lo que tienes que hacer, para no abrir otro mr y perder el histórico de esta conversación es pushear a tu rama. Una vez que haces eso, se actualiza automáticamente el mr, porque detecta el cambio. Una vez hecho eso, nos avisa en esta conversación y así podemos seguir. Es normal que salga raro al principio, pero para eso es un repo de prueba. Imagínate las que podríamos liar si esto fuese un repo de producción xD

2022-11-11 17:05 UTC, iagudo-d commented
Vale, la semana que  viene si no tienes inconveniente, hablamos del tema,
porque mi pretensión no era cerrar el pull-request y su histórico, pero no
sabía que al hacer el fetch y el mergue en mi propio fork se cargaba el
anterior request.xD

El vie., 11 nov. 2022 17:58, Bruno Azuara ***@***.***>
escribió:

> Claro, sin problema, por eso te pregunto que porqué haces un force. Lo que
> tienes que hacer, para no abrir otro mr y perder el histórico de esta
> conversación es pushear a tu rama. Una vez que haces eso, se actualiza
> automáticamente el mr, porque detecta el cambio. Una vez hecho eso, nos
> avisa en esta conversación y así podemos seguir. Es normal que salga raro
> al principio, pero para eso es un repo de prueba. Imagínate las que
> podríamos liar si esto fuese un repo de producción xD
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/42-Madrid-Maker-League/github_colab/pull/30#issuecomment-1311946941>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/A3A74GHE3ZN5U2ZWA4DMV5TWHZ3L7ANCNFSM6AAAAAAR243LJA>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>